name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci

      - name: Run lint
        run: pnpm run lint

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Run build
        run: pnpm run build